version: '3.3'

services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    ports:
      - '8081:8080'
    volumes:
      - ~/docker/volumes/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ~/docker/volumes/StirlingPDF/extraConfigs:/configs
      - ~/docker/volumes/StirlingPDF/customFiles:/customFiles/
      - ~/docker/volumes/StirlingPDF/logs:/logs/
      - ~/docker/volumes/StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_US
