personality = "pragmatic"
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"

[tui]
status_line = [ "codex-version", "model-name", "model-with-reasoning", "current-dir", "project-root", "git-branch", "context-used", "context-window-size", "five-hour-limit", "weekly-limit" ]
notifications = true

[features]
use_linux_sandbox_bwrap = true
multi_agent = true
apps = true

[windows]
sandbox = "elevated"

[plugins."github@openai-curated"]
enabled = true

[mcp_servers.serena]
command = "uvx"
args = [ "--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server" ]

[mcp_servers.context7]
command = "npx"
args = [ "-y", "@upstash/context7-mcp" ]

