[theme]
builtin = "Nord"
mode = "light"

[control_center]
sidebar = "full"
sidebar_section = "full"

[dock]
enabled = true
icon_size = 36
radius = 8
reserve_space = false
show_dots = true
smart_auto_hide = true
font_family = "Pretendard"

[shell]
polkit_agent = true

[bar.default]
capsule = true
capsule_fill = "shadow"
capsule_radius = 10
capsule_thickness = 0.75
start = ["workspaces"]
center = ["active_window"]
concave_edge_corners = false
font_family = "D2CodingLigature Nerd Font"
margin_ends = 4
padding = 12
radius = 8
radius_top_left = 0
radius_top_right = 0
end = ["group:g1", "group:g3", "group:g2", "clock", "group:g4"]

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "shadow"
id = "g1"
members = ["tray", "notifications", "clipboard", "lock_keys"]
opacity = 1.0
padding = 6.0

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "shadow"
id = "g2"
members = ["volume", "brightness", "battery"]
opacity = 1.0
padding = 6.0

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "shadow"
id = "g3"
members = ["network", "bluetooth"]
opacity = 1.0
padding = 6.0

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "shadow"
id = "g4"
members = ["control-center", "session"]
opacity = 1.0
padding = 6.0
radius = 10.0


[widget.battery]
hide_when_full = true
show_label = false

[widget.brightness]
capsule = true
show_label = false

[widget.network]
show_label = false

[widget.tray]
drawer = true
drawer_columns = 4
pinned = ["kime"]

[widget.volume]
show_label = false

[widget.clock]
format = "{:%-I:%M %p}"

[widget.lock_keys]
display = "full"
hide_when_off = true
show_scroll_lock = true
