#:schema https://mise.jdx.dev/schema/mise.json
[tools]
# Programming Languages
bun = "latest"
# clojure = "latest"
deno = "latest"
go = "latest"
rust = "latest"

# CLI Tools
act = "latest"
bat = "latest"
ctop = "latest"
delta = "latest"
difftastic = "latest"
direnv = "latest"
eza = "latest"
fastfetch = "latest"
fzf = "latest"
hyperfine = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
oh-my-posh = "latest"
ripgrep = "latest"
rumdl = "latest"
typst = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"

# Text Editor
helix = "latest"
neovim = "latest"

[settings]
lockfile = true
