#:schema https://mise.jdx.dev/schema/mise.json
[tools]
# Programming Languages
bun  = "latest"
deno = "latest"
go   = "latest"
zig  = "latest"
# BEAM
elixir = "latest"
erlang = "latest"
gleam  = "latest"

# CLI Tools
act        = "latest"
ast-grep   = "latest"
bat        = "latest"
ctop       = "latest"
delta      = "latest"
difftastic = "latest"
direnv     = "latest"
eza        = "latest"
fastfetch  = "latest"
fzf        = "latest"
herdr      = "latest"
hyperfine  = "latest"
just       = "latest"
lazydocker = "latest"
lazygit    = "latest"
oh-my-posh = "latest"
ripgrep    = "latest"
rumdl      = "latest"
typst      = "latest"
uv         = "latest"
yq         = "latest"
zoxide     = "latest"

# Text Editor
helix  = "latest"
neovim = "latest"
