version: '3.8'

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    ports:
      - 3000:80
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    networks:
      - public

networks:
  public:
    name: public