[mgr]
linemode = "permissions"
ratio = [2, 3, 5]
show_hidden = true

[opener]
pager = [
  { run = 'bat --paging=always -- %s', block = true, desc = "Page with bat", for = "unix" },
]

[open]
prepend_rules = [{ mime = "text/*", use = ["edit", "pager", "reveal"] }]
