# ./local.toml
includes = []
packages = ["default"]

[files]
"configs\\.config" = { target = "~\\AppData\\Roaming", type = "symbolic" }
"configs\\.config\\oh-my-posh" = { target = "~\\.config\\oh-my-posh", type = "symbolic" }
"hosts\\windows\\configs" = { target = "~", type = "symbolic" }
"hosts\\windows\\powershell" = { target = "~\\Documents\\PowerShell", type = "symbolic" }

[variables]
