import = [
    # "~/.config/alacritty/github_dark.toml"
    "~/.config/alacritty/dimidium.toml"
    ]

[window]

dimensions = { columns = 120, lines = 36 }

[font]

normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 12
