version = 3

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Icon }} [{{ .UserName }}]'
    foreground = 'cyan'
    type = 'os'
    style = 'powerline'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = 'cyan'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    template = ' :: {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}'
    foreground = '#F1502F'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      fetch_status = true
      fetch_package_manager = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  # system::shell
  [[blocks.segments]]
    template = ' {{ .Name }} '
    foreground = 'cyan'
    type = "shell"
    style = "powerline"

  # Programming languages
  [[blocks.segments]]
    type = 'node'
    foreground = '#6CA35E'
    style = 'powerline'
    template = ' {{ if .PackageManagerIcon }}+{{ .PackageManagerIcon }} {{ end }} ({{ .Full }}) '

    [blocks.segments.properties]
      fetch_package_manager = true

  [[blocks.segments]]
    type = 'python'
    foreground = '#FFDE57'
    style = 'plain'
    template = ' {{ .Full }} '
    [blocks.segments.properties]
      display_mode = 'context'

  [[blocks.segments]]
    type = "rust"
    foreground = "#99908a"
    style = "powerline"
    template = " {{ .Full }} "

  [[blocks.segments]]
    type = "go"
    style = "powerline"
    foreground = "#7FD5EA"
    template = " {{ .Full }} "

  [[blocks.segments]]
    type = "haskell"
    style = "powerline"
    foreground = "#906cff"
    template = " {{ .Full }} "

  # system::root
  [[blocks.segments]]
    template = '| root |'
    foreground = 'red'
    type = 'root'
    style = 'plain'

  # time
  [[blocks.segments]]
    template = '{{ .CurrentDate | date .Format }}'
    foreground = 'default'
    type = 'time'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '$ '
    foreground = 'lightGreen'
    type = 'status'
    style = 'powerline'
    foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
